@baseUrl = http://localhost:8085

### Return authenticated user
GET {{baseUrl}}/api/v1/users/me
Content-Type: application/json


### List users
GET {{baseUrl}}/api/v1/users
Content-Type: application/json