version: '3.8'

networks:
  home-calendar-network:

volumes:
  home-calendar-data:

services:
  db:
    image: mongo:8.0.12
    container_name: home-calendar-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: home-calendar-db
    volumes:
      - home-calendar-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - home-calendar-network

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: home-calendar-api
    environment:
      MONGODB_CONNECTION_STRING: mongodb://admin:admin@home-calendar-api:27017
      MONGODB_DB_NAME: homecalendardb
    ports:
      - "8085:8080"
    depends_on:
      - db
    networks:
      - home-calendar-network
