quarkus:
  application:
    name: home-calendar-api
  log:
    level: INFO
    min-level: ALL
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{2.} - %m%n%e'
    category:
      "com.meln":
        level: INFO
