app:
  google:
    auth-redirect-uri: http://localhost:8085/api/v1/google/callback
    success-redirect: http://localhost:8085/api/v1/google/success
    failure-redirect: http://localhost:8085/api/v1/google/failed

quarkus:
  http:
    port: 8085
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://app_user:admin@localhost:27017/home-calendar-db?retryWrites=false}
    database: ${MONGODB_DB_NAME:home-calendar-db}
  log:
    console:
      level: DEBUG
    category:
      "com.meln":
        level: DEBUG
