quarkus:
  http:
    port: 8085
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://admin:admin@localhost:27017}
  log:
    console:
      level: DEBUG
    category:
      "com.meln":
        level: DEBUG
