quarkus:
  application:
    name: home-calendar-api
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING}
    database: ${MONGODB_DB_NAME}
  mongock:
    migrate-at-start: true
    transaction-enabled: false #todo: check me!
  oidc:
    application-type: service
    provider: google
    auth-server-url: https://accounts.google.com
    auth-type: bearer
    client-id: ${GOOGLE_CLIENT_ID}
    credentials:
      secret: ${GOOGLE_CLIENT_SECRET}
    token:
      issuer: https://accounts.google.com
      principal-claim: email
  http:
    auth:
      permission:
        public:
          paths:
            - /q/*
            - /health/*
            - /openapi
            - /swagger-ui/*
          policy: permit
        authenticated:
          paths: /*
          policy: authenticated
  scheduler:
    enabled: true
  cache:
    caffeine:
      "user-exists-cache":
        maximum-size: 5000
        expire-after-write: 60M
  log:
    level: INFO
    min-level: ALL
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{2.} - %m%n%e'
    category:
      "com.meln":
        level: INFO
