quarkus:
  application:
    name: home-calendar-api
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING}
    database: ${MONGODB_DB_NAME}
  mongock:
    migrate-at-start: true
    transaction-enabled: false #todo: check me!
  log:
    level: INFO
    min-level: ALL
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{2.} - %m%n%e'
    category:
      "com.meln":
        level: INFO
