app:
  google:
    auth-redirect-uri: http://localhost:8085/api/v1/google/callback
    success-redirect: http://localhost:8085/api/v1/google/success
    failure-redirect: http://localhost:8085/api/v1/google/failed

quarkus:
  http:
    port: 8085
  datasource:
    db-kind: postgresql
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:homecalendardb}
      driver: org.postgresql.Driver
      max-size: 20
      initial-size: 5
      telemetry: true
  hibernate-orm:
    database:
      generation: none            # Use Flyway for schema changes
      default-schema: public         # Your target schema
      globally-quoted-identifiers: true
    log:
      sql: false
      bind-parameters: false
  flyway:
    migrate-at-start: true
    table: flyway_schema_history
    schemas: public
    locations: filesystem:../../../../migrations
    connect-retries: 10
  log:
    console:
      level: DEBUG
    category:
      "com.meln":
        level: DEBUG
