quarkus:
  application:
    name: home-calendar-api
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING}
    database: ${MONGODB_DB_NAME}
  mongock:
    migrate-at-start: true
    transaction-enabled: false #todo: check me!
  oidc:
    provider: google
    application-type: WEB_APP
    auth-server-url: https://accounts.google.com
    client-id: ${GOOGLE_CLIENT_ID}
    credentials:
      secret: ${GOOGLE_CLIENT_SECRET}
    authentication:
      redirect-path: http://localhost:3000/oauth2/redirect
      scopes:
        - openid
        - email
        - profile
  log:
    level: INFO
    min-level: ALL
    console:
      format: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %c{2.} - %m%n%e'
    category:
      "com.meln":
        level: INFO
