quarkus:
  http:
    port: 8085
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING:mongodb://homecalendar_user:admin@localhost:27017/homecalendardb?retryWrites=false}
    database: ${MONGODB_DB_NAME:homecalendardb}
  mongock:
    migrate-at-start: true
    transaction-enabled: false
  log:
    console:
      level: DEBUG
    category:
      "com.meln":
        level: DEBUG
